### ISSUE TITLE
sudoers: user cannot use sudo when Runas_Spec is empty

### ISSUE THREAD

**Issue by japaric** [trifectatechfoundation/sudo-rs#134]
Relevant test: 

https://github.com/memorysafety/sudo-rs/blob/3dfdbaf4ef3a7721ded33511b629a8d5c5dc7b14/test-framework/sudo-compliance-tests/src/sudoers/run_as.rs#L7-L22

sudo-rs: `sudo true` as a regular user fails with "Error: Authentication("no permission")". however, `sudo -u $(whoami) true` as a regular user works. both commands work when the invoking user is root.

original sudo: all test cases pass

**Comment by squell** [comment]
Note: this is an edge case that we discussed very early on and were considering leaving out (unless we find a sudoers file out there that does this). Essentially you can only use `=()` syntax to *restrict* what a user can normally do without sudo, which doesn't make much sense.

**Comment by squell** [comment]
Postponing a decision on this to Milestone 3 (when we may implement more introspection in the sudoers file); but I suspect this may end up becoming a `wontfix`.

**Comment by squell** [comment]
NOTE: New versions of ogsudo have the same behaviour as sudo-rs. 🥳
