### ISSUE TITLE
Adding French to SECURITY.md

### ISSUE THREAD

**Issue by ghost** [trifectatechfoundation/sudo-rs#837]
I'd like to offer my services as a French speaker to the project. I would be willing to help translate messages in French, if needed.
This would just open up more people to reach out in their native language, if they wish.

**Comment by squell** [comment]
This user has deleted their GitHub account so we can no longer contact them. We have had no security messages since this issue was opened so the issue hasn't arisen yet (but we would prefer to handle security-sensitive messages internally in the team, anyway).
